[book]
title = "libMMU Documentation"
description = "libMMU is a Rust crate that aims to simplify the process of rebuilding virtual address spaces from a memory dump in an OS-agnostic way."
authors = [
    "standard3",
    "shard7",
    "Hokanosekai",
    "gobelinor",
    "Esgr0bar",
    "Bash62",
]
language = "en"

[rust]
edition = "2021"

[output.html]
mathjax-support = true
site-url = "/docs/"
git-repository-url = "https://github.com/Memoscopy/libMMU/tree/main/docs"
edit-url-template = "https://github.com/Memoscopy/libMMU/edit/main/docs/{path}"

[output.html.playground]
editable = true
line-numbers = true

[output.html.code.hidelines]
python = "~"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.redirect]
"/format/config.html" = "configuration/index.html"
